(defun erlang-export-at-point ()
  (interactive)
  (save-excursion
    (back-to-indentation)
    (let ((fun (erlang-get-function-name-and-arity)))
      (goto-char (point-min))
      (re-search-forward "^-export\\s *(")
      (search-forward "[")
      (backward-char)
      (forward-list)
      (backward-char)
      (if (looking-back "\\[ *" nil)
          (insert fun)
        (insert ", " fun)))))
